package au.org.intersect.faims.android.ui.dialog;

public enum DialogTypes {
	LOCATE_SERVER, FETCH_PROJECT_LIST, DOWNLOAD_PROJECT, CONFIRM_DOWNLOAD_PROJECT, LOCATE_SERVER_FAILURE, FETCH_PROJECT_LIST_FAILURE, DOWNLOAD_PROJECT_FAILURE, DOWNLOAD_PROJECT_ERROR

}
