package au.org.intersect.faims.android.ui.dialog;

public enum DialogType {
	CONFIRM_RENDER_PROJECT, CONFIRM_DOWNLOAD_PROJECT, BUSY_FETCHING_PROJECT_LIST, BUSY_LOCATING_SERVER, BUSY_DOWNLOADING_PROJECT, LOCATE_SERVER_FAILURE, FETCH_PROJECT_LIST_FAILURE, DOWNLOAD_PROJECT_FAILURE, DOWNLOAD_PROJECT_ERROR

}
